// * USER
export const LOGIN_USER = "LOGIN_USER";

// * JOBS
export const RECEIVE_JOBS = "RECEIVE_JOBS";
export const FETCH_JOBS = "FETCH_JOBS";
export const FILTERED_JOBS = "FILTERED_JOBS";
export const CLEAR_USER_JOB_FILTER_SELECTION =
  "CLEAR_USER_JOB_FILTER_SELECTION";
export const FAVORITES_JOBS = "FAVORITES_JOBS";

// * SINGLE JOB
export const RECEIVE_JOB = "RECEIVE_JOB";
export const FETCH_JOB = "FETCH_JOB";
export const ADD_JOB_TO_FAVORITES = "ADD_JOB_TO_FAVORITES";
export const REMOVE_JOB_FROM_FAVORITES = "REMOVE_JOB_FROM_FAVORITES";

// * ORGANIZATIONS
export const UNIQUE_ORGANIZATIONS = "UNIQUE_ORGANIZATIONS";
export const ADD_SELECTED_ORGANIZATIONS = "ADD_SELECTED_ORGANIZATIONS";
export const INCLUDE_JOB_BY_ORGANIZATION = "INCLUDE_JOB_BY_ORGANIZATION";

// * JOB TYPES
export const UNIQUE_JOB_TYPES = "UNIQUE_JOB_TYPES";
export const ADD_SELECTED_JOB_TYPES = "ADD_SELECTED_JOB_TYPES";
export const INCLUDE_JOB_BY_JOB_TYPE = "INCLUDE_JOB_BY_JOB_TYPE";

// * DEGREES
export const RECEIVE_DEGREES = "RECEIVE_DEGREES";
export const FETCH_DEGREES = "FETCH_DEGREES";
export const UNIQUE_DEGREES = "UNIQUE_DEGREES";
export const INCLUDE_JOB_BY_DEGREE = "INCLUDE_JOB_BY_DEGREE";
export const ADD_SELECTED_DEGREES = "ADD_SELECTED_DEGREES";

// * SKILLS AND QUALIFICATIONS
export const UPDATE_SKILLS_SEARCH_TERM = "UPDATE_SKILLS_SEARCH_TERM";
export const INCLUDE_JOB_BY_SKILL = "INCLUDE_JOB_BY_SKILL";

// * LOCATION
export const UPDATE_LOCATION_SEARCH_TERM = "UPDATE_LOCATION_SEARCH_TERM";
export const INCLUDE_JOB_BY_LOCATION = "INCLUDE_JOB_BY_LOCATION";
